// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var HelloWorld$HelloWorld = require("../src/HelloWorld.bs.js");

Jest.describe("Hello World", (function (param) {
        return Jest.test("says hello", (function (param) {
                      return Jest.Expect[/* toBe */2]("Hello, World!", Jest.Expect[/* expect */0](HelloWorld$HelloWorld.hello(/* () */0)));
                    }));
      }));

/*  Not a pure module */
